# Generated by Django 2.2.6 on 2019-11-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191106_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='account.Holiday'),
        ),
        migrations.AlterField(
            model_name='country',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='account.Holiday'),
        ),
        migrations.AlterField(
            model_name='region',
            name='holidays',
            field=models.ManyToManyField(blank=True, to='account.Holiday'),
        ),
    ]
