# Generated by Django 2.2.6 on 2019-11-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191106_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='st_line2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
