# Generated by Django 2.2.6 on 2019-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20191106_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_url',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
