# Generated by Django 2.2.6 on 2019-11-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20191106_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Holiday', 'verbose_name_plural': 'Holidays'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'WorkingHours', 'verbose_name_plural': 'WorkingHours'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Address'),
        ),
    ]
