# Generated by Django 2.2.7 on 2019-11-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191118_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='is_annual',
            field=models.BooleanField(default=False),
        ),
    ]
