# Generated by Django 2.2.7 on 2019-11-25 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_holiday_is_annual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Provider'),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Provider'),
        ),
    ]
