# Generated by Django 2.2.7 on 2019-11-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191125_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='time_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workinghours',
            name='time_to',
            field=models.TimeField(),
        ),
    ]
